// Per-(base, mode, dept) header columns lifted verbatim from the mockup
// `GiaodienMockup/Admin/Operation (KO có thư mục sales).html` (FLAT_COLS +
// EFA_CCD_HEADER + DUP_*_LCL + DO_FCD_HEADER).
//
// Single source of truth for the admin workbook column schemas. The BE seed
// generator reads the same constants when bootstrapping empty sheets so the
// FE and the persisted rows line up.
export type OpsBase = 'EFA' | 'FCF' | 'DO' | 'DUP' | 'D2D'
export type OpsMode = 'FCL' | 'LCL' | 'AIR'
export type OpsDept = 'GSD' | 'ECD' | 'TCD' | 'CCD' | 'DCD' | 'FCD' | 'ICD' | 'QCD'
export type OpsType = 'EXW' | 'FCA' | 'FCF' | 'DO' | 'DAP' | 'DDU' | 'DDP' | 'DUP'
export type OpsStatus = 'active' | 'pending' | 'done'

// EFA base header — 46 cols, lifted from `wbdata["EFA"][0]` in the mockup.
export const EFA_BASE_HEADER: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS1', 'OPS2', 'TERM', 'EFA+', 'TYPE', 'C. CODE',
  'SHIPPER', 'CNEE', 'LINER', 'AGENT', 'BOOKING NO#', 'REF#', 'HBL NO#', 'MBL NO#',
  'ETD', 'ETA', 'SI CUTOFF DATE', 'TIME', 'CY CUTOFF DATE', 'TIME', 'VOLUME', 'ROUTE',
  'VESSEL NAME', 'VOYAGE', 'BC SENT', 'PICKUP CONFIRMATION', 'PICKUP INFORMATION',
  'CONTAINER NO#', 'SEAL NO#', 'STUFFING COMPLETION', 'GATEIN', 'LOADING READINESS',
  'FREETIME CONFIRMATION', 'FREETIME TYPE', 'ATD', 'PRE-ALERT SENDING',
  'MBL RELEASE', 'HBL RELEASE', 'ATA', 'DAYS AFTER ATA', 'PICKUP DATE', 'RETURN DATE',
  'DONE',
]

// FCF base header — EFA layout with `EFA+` renamed to `FCF+` (slot index 6).
export const FCF_BASE_HEADER: string[] = EFA_BASE_HEADER.map((c, i) => (i === 6 ? 'FCF+' : c))

// DO base header — 37 cols, lifted from `opsBaseHeader('DO')` in the mockup.
export const DO_BASE_HEADER: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS', 'TERM', 'DO+', 'TYPE', 'C.CODE', 'SHIPPER', 'CNEE',
  'LINER', 'AGENT', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ETA', 'VESSEL NAME', 'VOYAGE',
  'CONTAINER NO#', 'SEAL NO#', 'PRE-ALERT RECIEPT', 'MBL CONFIRMATION', 'HBL CONFIRMATION',
  'FREETIME CONFIRMATION', 'FREETIME TYPE', 'MBL RELEASE', 'HBL RELEASE', 'MNF SUBMIT',
  'AN SENDING', 'ATA', 'DO RELEASE', 'DAYS AFTER ATA', 'PICKUP DATE', 'RETURN DATE',
  'DONE',
]

// DUP base header — matches `wbdata["DUP"][0]` in the mockup (72 cols, VN).
// D2D reuses this header verbatim per `opsBaseHeader('D2D')` in the mockup.
export const DUP_BASE_HEADER: string[] = [
  'CÔNG TY', 'SALESMAN', 'OFFICE\nCHI NHÁNH', 'NGƯỜI\nPHỤ\nTRÁCH', 'OPS TƯƠNG ỨNG',
  'LOẠI\nHÌNH', 'ĐIỀU\nKIỆN', 'CODE\nKHÁCH\nHÀNG', 'SHIPPER', 'CONSIGNEE', 'HÃNG\nTÀU',
  'ĐẠI\nLÝ', 'TUYẾN\nĐƯỜNG', 'VOLUME\nHÀNG', 'SỐ\nMBL', 'SỐ\nHBL', 'SỐ\nHỆ\nTHỐNG',
  'ATD\nTHỰC\nTẾ', 'ATA\nTHỰC\nTẾ', 'TÊN TÀU/\nSỐ CHUYẾN', 'SỐ\nCONTAINER', 'SỐ\nSEAL',
  'BÁO ĐẠI LÝ/CHI NHÁNH KO GIAO HÀNG NẾU CHƯA CHO PHÉP', 'NGÀY\nFILE\nSI',
  'NGÀY\nNHẬP\nCẢNG', 'NGÀY\nXONG\nHQ', 'XIN HÌNH ẢNH ĐỂ LÀM TỜ KHAI',
  'XÁC NHẬN CÓ C/O KHÔNG?', 'XÁC\nNHẬN\nMBL', 'XÁC\nNHẬN\nHBL', 'FREE\nTIME',
  'LOẠI\nFREE\nTIME', 'GỬI/\nNHẬN\nPRE-ALERT', 'NGÀY\nTHẢ\nBILL', 'NGÀY\nTRÌNH\nMNF',
  'NHẬN/\nGỬI\nAN', 'LỆNH\nLẤY\nXONG', 'HẠN LỆNH ĐẾN NGÀY',
  'THU PHÍ PHÁT SINH TRƯỚC GIAO HÀNG, KHÁCH LÀ RACHEL THÌ HỎI RACHEL, KHÁCH KHÁC THÌ ĐẢM BẢO PHẢI THU, KHÔNG THU THÌ CTY KHÔNG CHI TIỀN',
  'LÀM BIÊN BẢN GIAO HÀNG GỬI NHÀ XE \n(NHẬP NGÀY)', 'DEBIT CHI\nE', 'DEBIT THU \nI',
  'NGÀY THU \nI', 'HÓA ĐƠN THU \nI', 'NGÀY\nUPLOAD\nE', 'NGÀY CHI\nE',
  'HÓA ĐƠN CHI \nE', 'LIFT\nON', 'LIFT\nOFF', 'IFTT', 'TAX CFM', 'CÓ KTCN KO?',
  'XEM QUY TRINH KTCN', 'GHI CHÚ HẢI QUAN', 'SỐ\nTKHQ', 'NGÀY\nTKHQ',
  'CÓ KIỂM HÓA KHÔNG?', 'ĐÃ NỘP THUẾ CHƯA?', 'ĐÃ NỘP LỆ PHÍ HQ CHƯA?',
  'KHAI CSHT', 'NGÀY\nTHÔNG\nQUAN', 'THU TIỀN VỀ HẢI LUẬN KHÁCH CÓ PHẢI GIAO HÀNG LUÔN HAY CHỜ XÁC NHẬN',
  'GỬI KHÁCH BCT THÔNG QUAN', 'ĐƯỜNG CẤM TẢI KHÔNG?',
  'BÁO KHÁCH DỰ KIẾN GIAO HÀNG\n(NHẬP NGÀY)', 'NHÀ XE SỬ DỤNG',
  'PHÁT SINH SAU GIAO HÀNG, GHI CHI TIẾT PHÍ GÌ VÌ BAO NHIÊU, KHÔNG NHẬP CTY KHÔNG TRỪ',
  'THEO DÕI KIỂM TRA CHUYÊN NGÀNH',
  'BÁO KHÁCH HÀNG PHÍ PHÁT SINH VỀ THU TIỀN VỀ HOẶC FOLLOW TIẾP\nKHÔNG BÁO CTY KHÔNG TRỪ',
  'PHÍ PHÁT SINH SAU GIAO HÀNG ĐÃ THU VỀ (NHẬP NGÀY)\nKHÔNG THU CTY KHÔNG TRỪ',
  'LƯU Ý KHÁC', 'HOÀN\nTHÀNH',
]

// AIR base header — 28 cols, lifted from the mockup.
export const AIR_BASE_HEADER: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS', 'AIR+', 'TYPE', 'C. CODE', 'SHIPPER', 'CNEE',
  'AWB NO#', 'AGENT', 'REF#', 'ETD', 'ETA', 'FLIGHT', 'AIRLINE', 'PIECES',
  'GROSS WEIGHT', 'VOLUME', 'RATE', 'TOTAL', 'PRE-ALERT', 'ARRIVAL NOTICE',
  'CUSTOMS CLEARANCE', 'DELIVERY', 'PICKUP DATE', 'RETURN DATE', 'DONE',
]

// ---- Source column indexes (used to derive CCD/DCD/FCD variants) ----
// CCD/DCD share src = EFA[0..26] without the `EFA+` col (idx 6).
const EFA_CCD_SRC: number[] = EFA_BASE_HEADER.map((_, i) => i).filter((i) => i < 27 && i !== 6)
const EFA_DCD_SRC: number[] = EFA_CCD_SRC.slice()
// FCD = same minus the cutoff/volume/route/vessel slots (19..22).
const EFA_FCD_SRC: number[] = EFA_CCD_SRC.filter((i) => ![19, 20, 21, 22].includes(i))

const FCF_DCD_SRC: number[] = FCF_BASE_HEADER.map((_, i) => i).filter((i) => i < 27)
const FCF_FCD_SRC: number[] = [
  ...FCF_BASE_HEADER.map((_, i) => i).filter((i) => i <= 18),
  23, 24, 25, 26,
]

const pick = (base: string[], src: number[], tail: string[]): string[] =>
  src.map((i) => base[i]).concat(tail)

// ---- Per-(base, dept) headers (FCL — base leaf). LCL variants below. ----
const EFA_CCD_HEADER = pick(EFA_BASE_HEADER, EFA_CCD_SRC, [
  'ACCESS CHECK', 'TRUCK SCHEDULE', 'TRUCK COMPANY', 'PICKUP INFORMATION',
  'STUFFING COMPLETION', 'GATEIN', 'CDS NO#', 'CDS DATE', 'CDS RESULT',
  'TAX APPLICABLE', 'CLEARANCE DATE', 'CDS FEE PAYMENT', 'RETURN DOCS', 'DONE',
])
const EFA_DCD_HEADER = pick(EFA_BASE_HEADER, EFA_DCD_SRC, [
  'SI SUBMIT', 'MBL APPROVAL', 'HBL APPROVAL', 'ATD', 'MBL RELEASE', 'HBL RELEASE',
  'DONE',
])
const EFA_FCD_HEADER = pick(EFA_BASE_HEADER, EFA_FCD_SRC, [
  'EXPENSE DEBIT', 'EXPENSE PAYMENT', 'EXPENSE INVOICE',
  'INCOME DEBIT', 'INCOME RECEIPT', 'INCOME INVOICE',
  'TAX CONFIRM', 'DONE',
])

const FCF_DCD_HEADER = pick(FCF_BASE_HEADER, FCF_DCD_SRC, [
  'SI SUBMIT', 'MBL APPROVAL', 'HBL APPROVAL', 'ATD', 'MBL RELEASE', 'HBL RELEASE',
  'DONE',
])
const FCF_FCD_HEADER = pick(FCF_BASE_HEADER, FCF_FCD_SRC, [
  'EXPENSE DEBIT', 'EXPENSE PAYMENT', 'EXPENSE INVOICE',
  'INCOME DEBIT', 'INCOME RECEIPT', 'INCOME INVOICE',
  'TAX CONFIRM', 'DONE',
])

const DO_FCD_HEADER: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS', 'TERM', 'DO+', 'TYPE', 'C.CODE', 'SHIPPER', 'CNEE',
  'LINER', 'AGENT', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ETA', 'VESSEL NAME', 'VOYAGE',
  'CONTAINER NO#', 'SEAL NO#', 'ATA', 'EXPENSE DEBIT', 'EXPENSE PAYMENT',
  'EXPENSE INVOICE', 'INCOME DEBIT', 'INCOME RECEIPT', 'INCOME INVOICE',
  'TAX CONFIRM', 'DONE',
]

// ---- DUP / D2D per-(mode, dept) ----
const DUP_ICD_HEADER_FCL: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS1', 'OPS2', 'TERM', 'DUP+', 'TYPE', 'C.CODE', 'SHIPPER',
  'CNEE', 'LINER', 'AGENT', 'ROUTE', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ETA',
  'VESSEL NAME', 'VOYAGE', 'CONTAINER/SEAL NO#', 'PRE-ALERT RECEIPT',
  'MBL CONFIRMATION', 'HBL CONFIRMATION', 'CLEARANCE DOCS CONFIRMATION',
  'EXTRA PROCEDURES', 'FREETIME CONFIRMATION', 'FREETIME TYPE', 'MBL RELEASE',
  'HBL RELEASE', 'MNF SUBMIT', 'AN SENDING', 'DO READINESS', 'DO VALIDATION',
  'CDS NO#', 'CDS DATE', 'CLEARANCE COMPLETION', 'TRUCK SCHEDULE', 'TRUCK COMPANY',
  'DELIVERY INFORMATION', 'PICKUP DATE', 'RETURN DATE', 'DONE',
]
const DUP_CCD_HEADER_FCL: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS1', 'OPS2', 'TERM', 'DUP+', 'TYPE', 'C.CODE', 'SHIPPER',
  'CNEE', 'LINER', 'AGENT', 'ROUTE', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ETA',
  'VESSEL NAME', 'VOYAGE', 'CONTAINER/SEAL NO#', 'PRE-ALERT RECEIPT',
  'MBL CONFIRMATION', 'HBL CONFIRMATION', 'CLEARANCE DOCS CONFIRMATION',
  'EXTRA PROCEDURES', 'CDS DRAFT CONFIRMATION', 'CDS NO#', 'CDS DATE', 'CDS RESULT',
  'ATA', 'TAX PAYMENT', 'CDS FEE PAYMENT', 'IFTT PAYMENT', 'CLEARANCE COMPLETION',
  'DOCS RETURN', 'DONE',
]
const DUP_TCD_HEADER_FCL: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS1', 'OPS2', 'TERM', 'DUP+', 'TYPE', 'C.CODE', 'SHIPPER',
  'CNEE', 'LINER', 'AGENT', 'ROUTE', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ATA',
  'VESSEL NAME', 'VOYAGE', 'CONTAINER/SEAL NO#', 'CDS NO#', 'CDS DATE', 'TAX PAYMENT',
  'CLEARANCE COMPLETION', 'DELIVERY APPROVAL', 'ACCESS CHECK', 'TRUCK SCHEDULE',
  'TRUCK COMPANY', 'DELIVERY INFORMATION', 'PICKUP DATE', 'RETURN DATE', 'DONE',
]
const DUP_ICD_HEADER_LCL: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS1', 'OPS2', 'TERM', 'DUP+', 'TYPE', 'C.CODE', 'SHIPPER',
  'CNEE', 'CARRIER', 'AGENT', 'ROUTE', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ETA',
  'VESSEL NAME', 'VOYAGE', 'CONTAINER NO#', 'SEAL NO#', 'PRE-ALERT RECEIPT',
  'MBL CONFIRMATION', 'HBL CONFIRMATION', 'CLEARANCE DOCS CONFIRMATION',
  'EXTRA PROCEDURES', 'MBL RELEASE', 'HBL RELEASE', 'MNF SUBMIT', 'AN SENDING',
  'DO READINESS', 'CDS NO#', 'CDS DATE', 'CLEARANCE COMPLETION', 'TRUCK SCHEDULE',
  'TRUCK COMPANY', 'DELIVERY INFORMATION', 'PICKUP DATE', 'DONE',
]
const DUP_CCD_HEADER_LCL: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS1', 'OPS2', 'TERM', 'DUP+', 'TYPE', 'C.CODE', 'SHIPPER',
  'CNEE', 'CARRIER', 'AGENT', 'ROUTE', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ETA',
  'VESSEL NAME', 'VOYAGE', 'CONTAINER NO#', 'SEAL NO#', 'PRE-ALERT RECEIPT',
  'MBL CONFIRMATION', 'HBL CONFIRMATION', 'CLEARANCE DOCS CONFIRMATION',
  'EXTRA PROCEDURES', 'CDS DRAFT CONFIRMATION', 'CDS NO#', 'CDS DATE', 'CDS RESULT',
  'ATA', 'TAX PAYMENT', 'CDS FEE PAYMENT', 'IFTT PAYMENT', 'CLEARANCE COMPLETION',
  'DOCS RETURN', 'DONE',
]
const DUP_TCD_HEADER_LCL: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS1', 'OPS2', 'TERM', 'DUP+', 'TYPE', 'C.CODE', 'SHIPPER',
  'CNEE', 'LINER', 'AGENT', 'ROUTE', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ATA',
  'VESSEL NAME', 'VOYAGE', 'CONTAINER/SEAL NO#', 'CDS NO#', 'CDS DATE', 'TAX PAYMENT',
  'CLEARANCE COMPLETION', 'DELIVERY APPROVAL', 'ACCESS CHECK', 'TRUCK SCHEDULE',
  'TRUCK COMPANY', 'DELIVERY INFORMATION', 'PICKUP DATE', 'DONE',
]
const DUP_FCD_HEADER: string[] = [
  'BU', 'SALES', 'BRANCH', 'OPS1', 'OPS2', 'TERM', 'DUP+', 'TYPE', 'C.CODE', 'SHIPPER',
  'CNEE', 'CARRIER', 'AGENT', 'ROUTE', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ETA',
  'VESSEL NAME', 'VOYAGE', 'CONTAINER NO#', 'SEAL NO#', 'EXPENSE DEBIT',
  'EXPENSE PAYMENT', 'EXPENSE INVOICE', 'INCOME DEBIT', 'INCOME RECEIPT',
  'INCOME INVOICE', 'TAX CONFIRM', 'DONE',
]

const AIR_FLAT_COLS: Partial<Record<OpsType, Partial<Record<OpsDept, string[]>>>> = {
  EXW: {
    GSD: ["TIME","EXTRA SERVICE","JOB NO#","ECD OPS","CLIENT","DEALT INFO","NOTICE","EXW+","SENT ECD","ACTION"],
    ECD: ["TIME","BU","DEALT INFO","EXTRA SERVICE","PAYMENT REQUEST","NOTICE","SALES","JOB NO#","ECD OPS","EXW+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DEST. AGENT","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","CUTOFF DETAIL","VOLUME","ROUTE","FLIGHT NO#","BC SENT","PICKUP DETAIL","TRUCKING INFO","AWB DETAIL","ATD","PRE-ALERT SENDING","AWB RELEASE","ATA","PICKUP STATUS","ACTION"],
    TCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ECD OPS","TCD OPS","CLIENT","SHIPPER","CNEE","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","CUTOFF DETAIL","VOLUME","ROUTE","FLIGHT NO#","PICKUP DETAIL","TRUCKING INFO","ACTION"],
    CCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ECD OPS","CCD OPS","CLIENT","SHIPPER","CNEE","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","CUTOFF DETAIL","VOLUME","ROUTE","FLIGHT NO#","PICKUP DETAIL","TRUCKING INFO","CLEARANCE DOCS APPROVAL","CLEARANCE DETAIL","ACTION"],
    DCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ECD OPS","DCD OPS","EXW+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DEST. AGENT","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","CUTOFF DETAIL","VOLUME","ROUTE","FLIGHT NO#","PICKUP DETAIL","TRUCKING INFO","SI SUBMIT","AWB DETAIL","ATD","AWB RELEASE","ACTION"],
    FCD: ["TIME","BU","DEALT INFO","EXPENSE/COLLECT LIST","NOTICE","SALES","ECD OPS","EXW+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DEST. AGENT","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","VOLUME","ROUTE","FLIGHT NO#","PICKUP DETAIL","TRUCKING INFO","ATD","ACTION"],
  },
  FCA: {
    GSD: ["TIME","EXTRA SERVICE","JOB NO#","ECD OPS","CLIENT","DEALT INFO","NOTICE","FCA+","SENT ECD","ACTION"],
    ECD: ["TIME","BU","DEALT INFO","EXTRA SERVICE","PAYMENT REQUEST","NOTICE","SALES","JOB NO#","ECD OPS","FCA+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","CUT OFF DETAIL","VOLUME","ROUTE","FLIGHT NO#","BC SENT","PICKUP DETAIL","TRUCKING INFO","AWB DETAIL","ATD","PRE-ALERT SENDING","AWB RELEASE","ATA","PICKUP STATUS","ACTION"],
    TCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ECD OPS","TCD OPS","CLIENT","SHIPPER","CNEE","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","CUT OFF DETAIL","VOLUME","ROUTE","FLIGHT NO#","PICKUP DETAIL","TRUCKING INFO","ACTION"],
    DCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ECD OPS","DCD OPS","FCA+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","CUT OFF DETAIL","VOLUME","ROUTE","FLIGHT NO#","PICKUP DETAIL","TRUCKING INFO","SI SUBMIT","AWB DETAIL","ATD","AWB RELEASE","ACTION"],
    FCD: ["TIME","BU","DEALT INFO","EXPENSE/COLLECT LIST","NOTICE","SALES","ECD OPS","FCA+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","VOLUME","ROUTE","FLIGHT NO#","PICKUP DETAIL","TRUCKING INFO","ATD","ACTION"],
  },
  FCF: {
    GSD: ["TIME","EXTRA SERVICE","JOB NO#","ECD OPS","CLIENT","DEALT INFO","NOTICE","FCF+","SENT ECD","ACTION"],
    ECD: ["TIME","BU","DEALT INFO","EXTRA SERVICE","PAYMENT REQUEST","NOTICE","SALES","JOB NO#","ECD OPS","FCF+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","CUT OFF DETAIL","VOLUME","ROUTE","FLIGHT NO#","BC SENT","AWB DETAIL","ATD","PRE-ALERT SENDING","AWB RELEASE","ATA","PICKUP STATUS","ACTION"],
    DCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ECD OPS","DCD OPS","FCF+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","CUT OFF DETAIL","VOLUME","ROUTE","FLIGHT NO#","SI SUBMIT","AWB DETAIL","ATD","AWB RELEASE","ACTION"],
    FCD: ["TIME","BU","DEALT INFO","EXPENSE/COLLECT LIST","NOTICE","SALES","ECD OPS","FCF+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","BC NO#","REF#","HAWB NO#","MAWB NO#","ETD","ETA","VOLUME","ROUTE","FLIGHT NO#","ATD","ACTION"],
  },
  DO: {
    GSD: ["TIME","EXTRA SERVICE","JOB NO#","ICD OPS","CLIENT","DEALT INFO","NOTICE","DO+","SENT ICD","ACTION"],
    ICD: ["TIME","BU","DEALT INFO","EXTRA SERVICE","PAYMENT REQUEST","NOTICE","SALES","JOB NO#","ICD OPS","DO+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","REF#","HAWB NO#","MAWB NO#","VOLUME","ROUTE","FLIGHT NO#","ATD","ETA","PRE-ALERT CONFIRMATION","CONT/SEAL INFO","MANIFEST SUBMIT","ARRIVAL NOTICE SENDING","ATA","DO VALIDITY","DO RELEASE","PICKUP STATUS","ACTION"],
    FCD: ["TIME","BU","DEALT INFO","EXPENSE/COLLECT LIST","NOTICE","SALES","ICD OPS","DO+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","REF#","HAWB NO#","MAWB NO#","ATD","ATA","VOLUME","ROUTE","FLIGHT NO#","ARRIVAL NOTICE SENDING","ACTION"],
  },
  DAP: {
    GSD: ["TIME","EXTRA SERVICE","JOB NO#","ICD OPS","CLIENT","DEALT INFO","NOTICE","DAP+","SENT ICD","ACTION"],
    ICD: ["TIME","BU","DEALT INFO","EXTRA SERVICE","PAYMENT REQUEST","NOTICE","SALES","JOB NO#","ICD OPS","DAP+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","REF#","HAWB NO#","MAWB NO#","VOLUME","ROUTE","FLIGHT NO#","ATD","ETA","PRE-ALERT CONFIRMATION","CONT/SEAL INFO","DELIVERY DETAIL","MANIFEST SUBMIT","ARRIVAL NOTICE SENDING","ATA","DO VALIDITY","PICKUP STATUS","ACTION"],
    TCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ICD OPS","TCD OPS","CLIENT","SHIPPER","CNEE","DESTINATION AGENT","AIRLINE","REF#","HAWB NO#","MAWB NO#","VOLUME","ROUTE","FLIGHT NO#","ATD","ATA","DELIVERY DETAIL","DO VALIDITY","TRUCKING INFO","ACTION"],
    FCD: ["TIME","BU","DEALT INFO","EXPENSE/COLLECT LIST","NOTICE","SALES","ICD OPS","DAP+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","REF#","HAWB NO#","MAWB NO#","ATD","ATA","VOLUME","ROUTE","FLIGHT NO#","DELIVERY DETAIL","TRUCKING INFO","ACTION"],
  },
  DDU: {
    GSD: ["TIME","EXTRA SERVICE","JOB NO#","ICD OPS","CLIENT","DEALT INFO","NOTICE","DDU+","SENT ICD","ACTION"],
    ICD: ["TIME","BU","DEALT INFO","EXTRA SERVICE","PAYMENT REQUEST","NOTICE","SALES","JOB NO#","ICD OPS","DDU+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","REF#","HAWB NO#","MAWB NO#","VOLUME","ROUTE","FLIGHT NO#","ATD","ETA","PRE-ALERT CONFIRMATION","CONT/SEAL INFO","DELIVERY DETAIL","MANIFEST SUBMIT","ARRIVAL NOTICE SENDING","ATA","DO VALIDITY","PICKUP STATUS","ACTION"],
    CCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ICD OPS","CCD OPS","CLIENT","SHIPPER","CNEE","AIRLINE","REF#","HAWB NO#","MAWB NO#","VOLUME","ROUTE","FLIGHT NO#","ATD","ETA","PRE-ALERT CONFIRMATION","CONT/SEAL INFO","ATA","DO VALIDITY","CLEARANCE DOCS APPROVAL","CLEARANCE DETAIL","ACTION"],
    TCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ICD OPS","TCD OPS","CLIENT","SHIPPER","CNEE","AIRLINE","REF#","HAWB NO#","MAWB NO#","VOLUME","ROUTE","FLIGHT NO#","ATD","ATA","DELIVERY DETAIL","DO VALIDITY","CLEARANCE DETAIL","TRUCKING INFO","ACTION"],
    FCD: ["TIME","BU","DEALT INFO","EXPENSE/COLLECT LIST","NOTICE","SALES","ICD OPS","DDU+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","REF#","HAWB NO#","MAWB NO#","ATD","ATA","VOLUME","ROUTE","FLIGHT NO#","TRUCKING INFO","ACTION"],
  },
  DDP: {
    GSD: ["TIME","EXTRA SERVICE","JOB NO#","ICD OPS","CLIENT","DEALT INFO","NOTICE","DDP+","SENT ICD","ACTION"],
    ICD: ["TIME","BU","DEALT INFO","EXTRA SERVICE","PAYMENT REQUEST","NOTICE","SALES","JOB NO#","ICD OPS","DDP+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","REF#","HAWB NO#","MAWB NO#","VOLUME","ROUTE","FLIGHT NO#","ATD","ETA","PRE-ALERT CONFIRMATION","CONT/SEAL INFO","DELIVERY DETAIL","MANIFEST SUBMIT","ARRIVAL NOTICE SENDING","ATA","DO VALIDITY","PICKUP STATUS","ACTION"],
    CCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ICD OPS","CCD OPS","CLIENT","SHIPPER","CNEE","AIRLINE","REF#","HAWB NO#","MAWB NO#","VOLUME","ROUTE","FLIGHT NO#","ATD","ETA","PRE-ALERT CONFIRMATION","CONT/SEAL INFO","ATA","DO VALIDITY","CLEARANCE DOCS APPROVAL","CLEARANCE DETAIL","ACTION"],
    TCD: ["TIME","BU","DEALT INFO","PAYMENT REQUEST","NOTICE","SALES","ICD OPS","TCD OPS","CLIENT","SHIPPER","CNEE","AIRLINE","REF#","HAWB NO#","MAWB NO#","VOLUME","ROUTE","FLIGHT NO#","ATD","ATA","DELIVERY DETAIL","DO VALIDITY","CLEARANCE DETAIL","TRUCKING INFO","ACTION"],
    FCD: ["TIME","BU","DEALT INFO","EXPENSE/COLLECT LIST","NOTICE","SALES","ICD OPS","DDP+","CLIENT","SHIPPER","CNEE","ORIGIN AGENT","DESTINATION AGENT","AIRLINE","REF#","HAWB NO#","MAWB NO#","ATD","ATA","VOLUME","ROUTE","FLIGHT NO#","TRUCKING INFO","ACTION"],
  },
}

const LCL_FLAT_COLS: Partial<Record<OpsType, Partial<Record<OpsDept, string[]>>>> = {
  EXW: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ECD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'EXW+', 'SENT ECD', 'ACTION'],
    ECD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ECD OPS', 'EXW+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DEST. AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUTOFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'BC SENT', 'PICKUP DETAIL', 'TRUCKING INFO', 'BILL DETAIL', 'ATD', 'PRE-ALERT SENDING', 'BILL RELEASE', 'ATA', 'PICKUP STATUS', 'ACTION'],
    TCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'TCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUTOFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCKING INFO', 'ACTION'],
    CCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'CCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUTOFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCKING INFO', 'CLEARANCE DOCS APPROVAL', 'CLEARANCE DETAIL', 'ACTION'],
    DCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'DCD OPS', 'EXW+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DEST. AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUTOFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCKING INFO', 'SI SUBMIT', 'BILL DETAIL', 'ATD', 'BILL RELEASE', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ECD OPS', 'EXW+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DEST. AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCKING INFO', 'ATD', 'ACTION'],
  },
  FCA: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ECD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'FCA+', 'SENT ECD', 'ACTION'],
    ECD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ECD OPS', 'FCA+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'BC SENT', 'PICKUP DETAIL', 'TRUCKING INFO', 'BILL DETAIL', 'ATD', 'PRE-ALERT SENDING', 'BILL RELEASE', 'ATA', 'PICKUP STATUS', 'ACTION'],
    TCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'TCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCKING INFO', 'ACTION'],
    DCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'DCD OPS', 'FCA+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCKING INFO', 'SI SUBMIT', 'BILL DETAIL', 'ATD', 'BILL RELEASE', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ECD OPS', 'FCA+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCKING INFO', 'ATD', 'ACTION'],
  },
  FCF: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ECD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'FCF+', 'SENT ECD', 'ACTION'],
    ECD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ECD OPS', 'FCF+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'BC SENT', 'BILL DETAIL', 'ATD', 'PRE-ALERT SENDING', 'BILL RELEASE', 'ATA', 'PICKUP/RETURN STATUS', 'ACTION'],
    DCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'DCD OPS', 'FCF+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'SI SUBMIT', 'BILL DETAIL', 'ATD', 'BILL RELEASE', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ECD OPS', 'FCF+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ACTION'],
  },
  DO: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ICD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'DO+', 'SENT ICD', 'ACTION'],
    ICD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ICD OPS', 'DO+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'MANIFEST SUBMIT', 'ARRIVAL NOTICE SENDING', 'ATA', 'DO VALIDITY', 'DO RELEASE', 'PICKUP STATUS', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ICD OPS', 'DO+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ATA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ARRIVAL NOTICE SENDING', 'ACTION'],
  },
  DAP: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ICD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'DAP+', 'SENT ICD', 'ACTION'],
    ICD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ICD OPS', 'DAP+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'DELIVERY DETAIL', 'MANIFEST SUBMIT', 'ARRIVAL NOTICE SENDING', 'ATA', 'DO VALIDITY', 'PICKUP STATUS', 'ACTION'],
    TCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ICD OPS', 'TCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ATA', 'DELIVERY DETAIL', 'DO VALIDITY', 'TRUCKING INFO', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ICD OPS', 'DAP+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ATA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'TRUCKING INFO', 'ACTION'],
  },
  DDU: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ICD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'DDU+', 'SENT ICD', 'ACTION'],
    ICD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ICD OPS', 'DDU+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'DELIVERY DETAIL', 'MANIFEST SUBMIT', 'ARRIVAL NOTICE SENDING', 'ATA', 'DO VALIDITY', 'PICKUP STATUS', 'ACTION'],
    CCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ICD OPS', 'CCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'ATA', 'DO VALIDITY', 'CLEARANCE DOCS APPROVAL', 'CLEARANCE DETAIL', 'ACTION'],
    TCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ICD OPS', 'TCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ATA', 'DELIVERY DETAIL', 'DO VALIDITY', 'CLEARANCE DETAIL', 'TRUCKING INFO', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ICD OPS', 'DDU+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ATA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'TRUCKING INFO', 'ACTION'],
  },
  DDP: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ICD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'DDP+', 'SENT ICD', 'ACTION'],
    ICD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ICD OPS', 'DDP+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'DELIVERY DETAIL', 'MANIFEST SUBMIT', 'ARRIVAL NOTICE SENDING', 'ATA', 'DO VALIDITY', 'PICKUP STATUS', 'ACTION'],
    CCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ICD OPS', 'CCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'ATA', 'DO VALIDITY', 'CLEARANCE DOCS APPROVAL', 'CLEARANCE DETAIL', 'ACTION'],
    TCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ICD OPS', 'TCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ATA', 'DELIVERY DETAIL', 'DO VALIDITY', 'CLEARANCE DETAIL', 'TRUCKING INFO', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ICD OPS', 'DDP+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ATA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'TRUCKING INFO', 'ACTION'],
  },
}

const FLAT_COLS: Partial<Record<OpsType, Partial<Record<OpsDept, string[]>>>> = {
  EXW: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ECD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'EXW+', 'SENT ECD', 'ACTION'],
    ECD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ECD OPS', 'EXW+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUTOFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'BC SENT', 'PICKUP DETAIL', 'TRUCK & CONT/SEAL INFO', 'FREETIME CONFIRMATION', 'BILL DETAIL', 'ATD', 'PRE-ALERT SENDING', 'BILL RELEASE', 'ATA', 'PICKUP/RETURN STATUS', 'ACTION'],
    TCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ECD OPS', 'TCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUTOFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCK & CONT/SEAL INFO', 'ACTION'],
    CCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'CCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUTOFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCK & CONT/SEAL INFO', 'CLEARANCE DOCS APPROVAL', 'CLEARANCE DETAIL', 'ACTION'],
    DCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'DCD OPS', 'EXW+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUTOFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCK & CONT/SEAL INFO', 'SI SUBMIT', 'BILL DETAIL', 'ATD', 'BILL RELEASE', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ECD OPS', 'EXW+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCK & CONT/SEAL INFO', 'ATD', 'ACTION'],
  },
  FCA: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ECD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'FCA+', 'SENT ECD', 'ACTION'],
    ECD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ECD OPS', 'FCA+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'BC SENT', 'PICKUP DETAIL', 'TRUCK & CONT/SEAL INFO', 'FREETIME CONFIRMATION', 'BILL DETAIL', 'ATD', 'PRE-ALERT SENDING', 'BILL RELEASE', 'ATA', 'PICKUP/RETURN STATUS', 'ACTION'],
    TCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ECD OPS', 'TCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCK & CONT/SEAL INFO', 'ACTION'],
    DCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'DCD OPS', 'FCA+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCK & CONT/SEAL INFO', 'SI SUBMIT', 'BILL DETAIL', 'ATD', 'BILL RELEASE', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ECD OPS', 'FCA+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'PICKUP DETAIL', 'TRUCK & CONT/SEAL INFO', 'ATD', 'ACTION'],
  },
  FCF: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ECD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'FCF+', 'SENT ECD', 'ACTION'],
    ECD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ECD OPS', 'FCF+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'BC SENT', 'FREETIME CONFIRMATION', 'BILL DETAIL', 'ATD', 'PRE-ALERT SENDING', 'BILL RELEASE', 'ATA', 'PICKUP/RETURN STATUS', 'ACTION'],
    DCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ECD OPS', 'DCD OPS', 'FCF+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'CUT OFF DETAIL', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'SI SUBMIT', 'BILL DETAIL', 'ATD', 'BILL RELEASE', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ECD OPS', 'FCF+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'BC NO#', 'REF#', 'HBL NO#', 'MBL NO#', 'ETD', 'ETA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ACTION'],
  },
  DO: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ICD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'DO+', 'SENT ICD', 'ACTION'],
    ICD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ICD OPS', 'DO+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'MANIFEST SUBMIT', 'ARRIVAL NOTICE SENDING', 'ATA', 'DO VALIDITY', 'DO RELEASE', 'PICKUP/RETURN STATUS', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ICD OPS', 'DO+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ATA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'CONT/SEAL INFO', 'ARRIVAL NOTICE SENDING', 'ACTION'],
  },
  DUP: {
    GSD: ['EXTRA SERVICE', 'JOB NO#', 'OPS', 'CLIENT', 'DEALT INFO', 'REMINDER', 'SENT ICD', 'ACTION'],
    ICD: ['BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'REMINDER', 'SALES', 'OPS', 'DUP+', 'CLIENT', 'SHIPPER', 'CNEE', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'DELIVERY DETAILS', 'MANIFEST SUBMIT', 'ARRIVAL NOTICE SENDING', 'ATA', 'DO VALIDITY', 'PICKUP/RETURN STATUS', 'ACTION'],
    CCD: ['BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'REMINDER', 'SALES', 'OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'ARRIVAL NOTICE DETAIL', 'CONT/SEAL INFO', 'ATA', 'DO VALIDITY', 'CLEARANCE DETAIL', 'ACTION'],
    TCD: ['BU', 'DEALT INFO', 'PAYMENT REQUEST', 'REMINDER', 'SALES', 'OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ATA', 'DELIVERY DETAILS', 'DO VALIDITY', 'CLEARANCE DETAILS', 'TRUCK & CONT/SEAL INFO', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'JOB NO#', 'OPS', 'DAP+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ATA', 'DELIVERY DETAIL', 'TRUCK & CONT/SEAL INFO', 'ACTION'],
  },
  DAP: {
    GSD: ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ICD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', 'DAP+', 'SENT ICD', 'ACTION'],
    ICD: ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ICD OPS', 'DAP+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'DELIVERY DETAIL', 'MANIFEST SUBMIT', 'ARRIVAL NOTICE SENDING', 'ATA', 'DO VALIDITY', 'PICKUP STATUS', 'ACTION'],
    TCD: ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ICD OPS', 'TCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ATA', 'DELIVERY DETAIL', 'DO VALIDITY', 'TRUCK & CONT/SEAL INFO', 'ACTION'],
    FCD: ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ICD OPS', 'DAP+', 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ATA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'TRUCK & CONT/SEAL INFO', 'ACTION'],
  },
}

const hiddenOpsColumns = (base: OpsBase, mode: OpsMode, dept: OpsDept): Set<number> => {
  if ((base === 'EFA' || base === 'FCF') && dept === 'ECD') {
    if (base === 'FCF') {
      if (mode === 'FCL') return new Set([28, 29, 30, 31])
      if (mode === 'LCL') return new Set([28, 29, 30, 31, 34, 35, 36, 44])
      return new Set([30, 31])
    }
    if (mode === 'FCL') return new Set([30, 31, 34])
    if (mode === 'LCL') return new Set([30, 31, 35, 36, 44])
    return new Set([30, 31])
  }
  if (base === 'EFA' && dept === 'CCD' && mode === 'FCL') return new Set([30])
  if (base === 'DO' && dept === 'ICD') {
    if (mode === 'FCL') return new Set([20])
    if (mode === 'LCL') return new Set([24, 25, 34])
  }
  if (base === 'DO' && dept === 'FCD' && mode === 'LCL') return new Set([19, 20])
  return new Set()
}

const opsHeaderName = (base: OpsBase, mode: OpsMode, dept: OpsDept, index: number, raw: string): string => {
  if (base === 'EFA') {
    if (mode === 'LCL' && dept === 'ECD') {
      if (index === 11) return 'CARRIER'
      if (index === 21) return 'CFS CUTOFF DATE'
    }
    if (mode === 'FCL' && dept === 'ECD' && index === 32) return 'SI READINESS'
  } else if (base === 'FCF') {
    if (dept === 'ECD') {
      if (index === 32) return 'SI READINESS'
      if (mode === 'LCL' && index === 11) return 'CARRIER'
    }
  } else if (base === 'DO') {
    if (dept === 'ICD') {
      if (mode === 'FCL' && index === 19) return 'CONTAINER/SEAL NO#'
      if (mode === 'LCL' && index === 10) return 'CARRIER'
    } else if (dept === 'FCD' && mode === 'LCL' && index === 10) {
      return 'CARRIER'
    }
  }
  return raw === 'BILL APPROVAL' ? 'BILL DETAIL' : raw
}

const opsFlatHeaderLabel = (label: string) => label === 'BILL APPROVAL' ? 'BILL DETAIL' : label

const opsVisibleHeader = (base: OpsBase, mode: OpsMode, dept: OpsDept, header: string[]): string[] => {
  const hidden = hiddenOpsColumns(base, mode, dept)
  const visible = header
    .map((label, index) => ({ label: opsHeaderName(base, mode, dept, index, label), index }))
    .filter(({ index }) => !hidden.has(index))
    .map(({ label }) => opsFlatHeaderLabel(label))
  return visible[0] === 'TIME' ? visible.slice() : ['TIME', ...visible]
}

const opsFlatHeader = (header: string[]): string[] => {
  const renamed = header.map(opsFlatHeaderLabel)
  return renamed[0] === 'TIME' ? renamed : ['TIME', ...renamed]
}

// Lookup the mockup header for a (base, mode, dept) leaf.
function rawOpsHeaderFor(base: OpsBase, mode: OpsMode, dept: OpsDept, type?: OpsType | null): string[] {
  // Destination FCD follows the same operational schema as TCD for
  // DAP/DDU/DDP. Keeping one source schema also lets linked TCD rows align
  // field-for-field when they are mirrored into FCD.
  if (dept === 'FCD' && ['DAP', 'DDU', 'DDP'].includes(String(type || '').toUpperCase())) {
    return rawOpsHeaderFor(base, mode, 'TCD', type)
  }
  if (mode === 'FCL' && ['DDU', 'DDP'].includes(String(type || '').toUpperCase()) && dept === 'GSD') {
    const flow = `${String(type).toUpperCase()}+`
    return ['TIME', 'EXTRA SERVICE', 'JOB NO#', 'ICD OPS', 'CLIENT', 'DEALT INFO', 'NOTICE', flow, 'SENT ICD', 'ACTION']
  }
  if (mode === 'FCL' && ['DDU', 'DDP'].includes(String(type || '').toUpperCase()) && dept === 'ICD') {
    const flow = `${String(type).toUpperCase()}+`
    return ['TIME', 'BU', 'DEALT INFO', 'EXTRA SERVICE', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'JOB NO#', 'ICD OPS', flow, 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'DELIVERY DETAIL', 'MANIFEST SUBMIT', 'ARRIVAL NOTICE SENDING', 'ATA', 'DO VALIDITY', 'PICKUP STATUS', 'ACTION']
  }
  if (mode === 'FCL' && ['DDU', 'DDP'].includes(String(type || '').toUpperCase()) && dept === 'CCD') {
    const notice = String(type).toUpperCase() === 'DDU' ? ['NOTICE'] : []
    return ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', ...notice, 'SALES', 'ICD OPS', 'CCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ETA', 'PRE-ALERT CONFIRMATION', 'CONT/SEAL INFO', 'ATA', 'DO VALIDITY', 'CLEARANCE DOCS APPROVAL', 'CLEARANCE DETAIL', 'ACTION']
  }
  if (mode === 'FCL' && ['DDU', 'DDP'].includes(String(type || '').toUpperCase()) && dept === 'TCD') {
    return ['TIME', 'BU', 'DEALT INFO', 'PAYMENT REQUEST', 'NOTICE', 'SALES', 'ICD OPS', 'TCD OPS', 'CLIENT', 'SHIPPER', 'CNEE', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'ATD', 'ATA', 'DELIVERY DETAIL', 'DO VALIDITY', 'CLEARANCE DETAIL', 'TRUCK & CONT/SEAL INFO', 'ACTION']
  }
  if (mode === 'FCL' && ['DDU', 'DDP'].includes(String(type || '').toUpperCase()) && dept === 'FCD') {
    const flow = `${String(type).toUpperCase()}+`
    return ['TIME', 'BU', 'DEALT INFO', 'EXPENSE/COLLECT LIST', 'NOTICE', 'SALES', 'ICD OPS', flow, 'CLIENT', 'SHIPPER', 'CNEE', 'ORIGIN AGENT', 'DESTINATION AGENT', 'LINER', 'REF#', 'HBL NO#', 'MBL NO#', 'ATD', 'ATA', 'VOLUME', 'ROUTE', 'VESSEL/VOYAGE', 'TRUCK & CONT/SEAL INFO', 'ACTION']
  }
  const effectiveType = ['LCL', 'AIR'].includes(mode) ? type : type === 'DDU' || type === 'DDP' ? 'DUP' : type
  if (mode === 'LCL' && effectiveType) {
    const lcl = LCL_FLAT_COLS[effectiveType]?.[dept]
    if (lcl) return opsFlatHeader(lcl)
  }
  if (mode === 'AIR' && effectiveType) {
    const air = AIR_FLAT_COLS[effectiveType]?.[dept]
    if (air) return opsFlatHeader(air)
  }
  const flat = effectiveType ? FLAT_COLS[effectiveType]?.[dept] : null
  if (flat) return opsFlatHeader(flat)
  if (mode === 'AIR') return opsVisibleHeader(base, mode, dept, AIR_BASE_HEADER)
  if (base === 'EFA') {
    if (dept === 'CCD') return opsVisibleHeader(base, mode, dept, EFA_CCD_HEADER)
    if (dept === 'DCD') return opsVisibleHeader(base, mode, dept, EFA_DCD_HEADER)
    if (dept === 'FCD') return opsVisibleHeader(base, mode, dept, EFA_FCD_HEADER)
    return opsVisibleHeader(base, mode, dept, EFA_BASE_HEADER)
  }
  if (base === 'FCF') {
    if (dept === 'DCD') return opsVisibleHeader(base, mode, dept, FCF_DCD_HEADER)
    if (dept === 'FCD') return opsVisibleHeader(base, mode, dept, FCF_FCD_HEADER)
    return opsVisibleHeader(base, mode, dept, FCF_BASE_HEADER)
  }
  if (base === 'DO') {
    if (dept === 'FCD') return opsVisibleHeader(base, mode, dept, DO_FCD_HEADER)
    return opsVisibleHeader(base, mode, dept, DO_BASE_HEADER)
  }
  if (base === 'DUP' || base === 'D2D') {
    if (dept === 'FCD') return opsVisibleHeader(base, mode, dept, DUP_FCD_HEADER)
    if (mode === 'LCL') {
      if (dept === 'ICD') return opsVisibleHeader(base, mode, dept, DUP_ICD_HEADER_LCL)
      if (dept === 'CCD') return opsVisibleHeader(base, mode, dept, DUP_CCD_HEADER_LCL)
      if (dept === 'TCD') return opsVisibleHeader(base, mode, dept, DUP_TCD_HEADER_LCL)
    }
    if (dept === 'ICD') return opsVisibleHeader(base, mode, dept, DUP_ICD_HEADER_FCL)
    if (dept === 'CCD') return opsVisibleHeader(base, mode, dept, DUP_CCD_HEADER_FCL)
    if (dept === 'TCD') return opsVisibleHeader(base, mode, dept, DUP_TCD_HEADER_FCL)
    return opsVisibleHeader(base, mode, dept, DUP_BASE_HEADER)
  }
  return opsVisibleHeader(base, mode, dept, EFA_BASE_HEADER)
}

export function opsHeaderFor(base: OpsBase, mode: OpsMode, dept: OpsDept, type?: OpsType | null): string[] {
  const rawHeader = rawOpsHeaderFor(base, mode, dept, type)
  const normalizedType = String(type || '').toUpperCase()
  const mirrorsTcdSchema = String(dept || '').toUpperCase() === 'FCD' &&
    ['DAP', 'DDU', 'DDP'].includes(normalizedType)
  // DAP/DDU/DDP use one shared DO INFORMATION form. The date is stored inside
  // DO INFO, so a second DO VALIDITY column must not be generated downstream.
  const visibleHeader = ['DAP', 'DDU', 'DDP'].includes(normalizedType)
    ? rawHeader.map((label) => label === 'DO VALIDITY' ? 'DO INFO' : label)
    : rawHeader
  // Downstream worksheets own one assignee column. GSD additionally shows the
  // next department's linked assignee beside its own GSD column.
  const departmentOpsPattern = /^(?:(?:GSD|ECD|ICD|TCD|CCD|DCD|FCD|QCD) OPS|OPS[12]?)$/
  const firstOpsColumn = visibleHeader.findIndex((label) => departmentOpsPattern.test(String(label).toUpperCase()))
  const header = firstOpsColumn < 0
    ? visibleHeader
    : String(dept).toUpperCase() === 'GSD'
    ? visibleHeader.reduce<string[]>((result, label, index) => {
        if (!departmentOpsPattern.test(String(label).toUpperCase())) return [...result, label]
        if (index !== firstOpsColumn) return result
        const linkedOps = String(label).toUpperCase()
        return linkedOps === 'OPS' || linkedOps === 'GSD OPS'
          ? [...result, 'GSD']
          : [...result, 'GSD', linkedOps]
      }, [])
    : visibleHeader.reduce<string[]>((result, label, index) => {
        if (!departmentOpsPattern.test(String(label).toUpperCase())) return [...result, label]
        return index === firstOpsColumn ? [...result, `${String(dept).toUpperCase()} OPS`] : result
      }, [])
  const deptUpper = String(dept || '').toUpperCase()
  const orderedHeader = deptUpper === 'GSD' && String(type || '').toUpperCase() === 'EXW' && header.includes('EXW+')
    ? (() => {
        const withoutFlow = header.filter((label) => label !== 'EXW+')
        const ecdOpsColumn = withoutFlow.indexOf('ECD OPS')
        const insertAt = ecdOpsColumn >= 0 ? ecdOpsColumn + 1 : withoutFlow.indexOf('GSD') + 1
        return [...withoutFlow.slice(0, insertAt), 'EXW+', ...withoutFlow.slice(insertAt)]
      })()
    : header
  const headerWithJobNo = (['TCD', 'CCD'].includes(deptUpper) || mirrorsTcdSchema) && !orderedHeader.includes('JOB NO#')
    ? (() => {
        const salesColumn = orderedHeader.findIndex((label) => label === 'SALES')
        const insertAt = salesColumn >= 0 ? salesColumn + 1 : Math.max(0, orderedHeader.findIndex((label) => label === 'TIME') + 1)
        return [...orderedHeader.slice(0, insertAt), 'JOB NO#', ...orderedHeader.slice(insertAt)]
      })()
    : orderedHeader
  const headerWithMode = (!['TCD', 'CCD', 'DCD'].includes(deptUpper) && !mirrorsTcdSchema) || headerWithJobNo.includes('MODE')
    ? headerWithJobNo
    : (() => {
        const timeColumn = headerWithJobNo.findIndex((label) => label === 'TIME')
        const insertAt = timeColumn >= 0 ? timeColumn + 1 : 0
        return [...headerWithJobNo.slice(0, insertAt), 'MODE', ...headerWithJobNo.slice(insertAt)]
      })()
  if (headerWithMode.includes('NOTES')) return headerWithMode
  const actionColumn = headerWithMode.lastIndexOf('ACTION')
  const notesAt = actionColumn >= 0 ? actionColumn : headerWithMode.length
  return [...headerWithMode.slice(0, notesAt), 'NOTES', ...headerWithMode.slice(notesAt)]
}

export const OPS_TYPES_BY_BASE: Record<OpsBase, OpsType[] | null> = {
  EFA: ['EXW', 'FCA'],
  FCF: ['FCF'],
  DO: ['DO'],
  DUP: ['DAP', 'DDU', 'DDP', 'DUP'],
  D2D: null,
}

export const OPS_TERMS: OpsType[] = ['EXW', 'FCA', 'FCF', 'DO', 'DAP', 'DDU', 'DDP']

export const opsBaseForType = (type: OpsType | null | undefined): OpsBase => {
  if (type === 'FCF') return 'FCF'
  if (type === 'DO') return 'DO'
  if (type === 'DAP' || type === 'DDU' || type === 'DDP' || type === 'DUP') return 'DUP'
  return 'EFA'
}

export const OPS_PRIMARY_TYPE: Partial<Record<OpsBase, OpsType>> = {
  EFA: 'EXW',
  FCF: 'FCF',
  DO: 'DO',
  DUP: 'DUP',
}

export const OPS_DEPTS_BY_TYPE: Record<OpsType, OpsDept[]> = {
  EXW: ['GSD', 'ECD', 'TCD', 'CCD', 'DCD', 'FCD'],
  FCA: ['GSD', 'ECD', 'TCD', 'DCD', 'FCD'],
  FCF: ['GSD', 'ECD', 'DCD', 'FCD'],
  DO: ['GSD', 'ICD', 'FCD'],
  DAP: ['GSD', 'ICD', 'TCD', 'FCD'],
  DDU: ['GSD', 'ICD', 'CCD', 'TCD', 'FCD'],
  DDP: ['GSD', 'ICD', 'CCD', 'TCD', 'FCD'],
  DUP: ['GSD', 'ICD', 'CCD', 'TCD', 'FCD'],
}

export const OPS_DEPTS_BY_BASE: Record<OpsBase, OpsDept[]> = {
  EFA: ['ECD', 'CCD', 'TCD', 'DCD', 'FCD'],
  FCF: ['ECD', 'DCD', 'FCD'],
  DO: ['ICD', 'FCD'],
  DUP: ['ICD', 'CCD', 'TCD', 'FCD'],
  D2D: ['ECD', 'CCD', 'DCD', 'QCD', 'ICD', 'FCD'],
}

export const DEFAULT_OPS_DEPT: Record<OpsBase, OpsDept> = {
  EFA: 'GSD',
  FCF: 'GSD',
  DO: 'GSD',
  DUP: 'GSD',
  D2D: 'ECD',
}

export const stripOpsStatus = (sheetKey: string) =>
  String(sheetKey || '').replace(/#(?:DONE|PEND)$/i, '')

export const opsStatusOf = (sheetKey: string): OpsStatus => {
  const key = String(sheetKey || '').toUpperCase()
  if (key.endsWith('#DONE')) return 'done'
  if (key.endsWith('#PEND')) return 'pending'
  return 'active'
}

export const opsPrimaryType = (base: OpsBase): OpsType | null => OPS_PRIMARY_TYPE[base] || null

export const opsTypesOf = (base: OpsBase): OpsType[] =>
  OPS_TYPES_BY_BASE[base]?.slice() || []

export const opsDeptsFor = (base: OpsBase, type?: OpsType | null): OpsDept[] =>
  (type && OPS_DEPTS_BY_TYPE[type] ? OPS_DEPTS_BY_TYPE[type] : OPS_DEPTS_BY_BASE[base]).slice()

export function opsLeafKey(base: OpsBase, mode: OpsMode, type: OpsType | null | undefined, dept: OpsDept): string {
  const primary = opsPrimaryType(base)
  if (type && type !== primary) return `${base}::${mode}::${type}::${dept}`
  return `${base}::${mode}::${dept}`
}

export function opsStatusKey(leafKey: string, status: OpsStatus): string {
  const leaf = stripOpsStatus(leafKey)
  if (status === 'done') return `${leaf}#DONE`
  if (status === 'pending') return `${leaf}#PEND`
  return leaf
}

// Parse "BASE::MODE::DEPT", "BASE::MODE::TYPE::DEPT", plus #PEND/#DONE.
export function parseOpsKey(sheetKey: string): {
  base: OpsBase
  mode: OpsMode
  type: OpsType | null
  dept: OpsDept
  status: OpsStatus
} | null {
  const status = opsStatusOf(sheetKey)
  const parts = stripOpsStatus(sheetKey).split('::')
  if (![3, 4].includes(parts.length)) return null
  const [baseRaw, modeRaw] = parts
  if (!['EFA', 'FCF', 'DO', 'DUP', 'D2D'].includes(baseRaw)) return null
  if (!['FCL', 'LCL', 'AIR'].includes(modeRaw)) return null
  const base = baseRaw as OpsBase
  const mode = modeRaw as OpsMode
  const type = parts.length === 4 ? parts[2] as OpsType : opsPrimaryType(base)
  const dept = (parts.length === 4 ? parts[3] : parts[2]) as OpsDept
  const allowedTypes = OPS_TYPES_BY_BASE[base]
  if (allowedTypes && type && !allowedTypes.includes(type)) return null
  if (!allowedTypes && type) return null
  return { base, mode, type, dept, status }
}
